### ISSUE TITLE
CouchPotato TODO

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/NZBDash#65]
- [ ] Add the ability to view watching list
- [ ] Add the ability to search and add movies
- [ ] Add the ability to change the search quality of a movie
- [ ] Add the ability to Refresh a movie search
- [ ] Add the ability to remove a movie
- [ ] Add the ability to Restart CouchPotato application
