### ISSUE TITLE
Sonarr TODO

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/NZBDash#66]
- [ ] Add the ability to search and add TV Shows 
- [ ] Add the ability to change the monitoring status of a tv series
- [ ] Add the ability to view the Sonarr Calendar
- [ ] Add the ability to Restart Sonarr
