### ISSUE TITLE
NZBGet TODO

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/NZBDash#67]
- [ ] Add the ability to Pause downloads
- [ ] Add the ability to Pause download for set time
- [ ] Add the ability to Set download speed
- [ ] Add the ability to remove a NZB
- [ ] Add the ability to add a NZB
- [ ] Add the ability to Restart NZBGet
